### PR TITLE
Fix Tool Builder Bugs

### PR DESCRIPTION
**Pull request by ChinemeremChigbo**
## Notion ticket link

[[Tool Builder] Resolve Bugs](https://www.notion.so/uwblueprintexecs/Tool-Builder-Resolve-Bugs-34a528a36db746b7aa6d2ded9b9c3a43)

## Implementation description
- [x] Fix tool persistence bugs

## Steps to test
1. Add many self check questions to module self check
2.  Type into fields and change question types at random
3. Change related tools rapidly
4. Quickly Change question type
5. **Save the tool** and ensure no errors occur
6. Repeat steps 1 - 5 in random orders and ensure that no bugs are encountered

## What should reviewers focus on?
* Module persistence bugs

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

### CODE REVIEW

**Comment by ChinemeremChigbo** [comment]
Please let me know if you guys still notice and self check bugs whatsoever. These can be sometimes a little tricky to replicate so if you find any that this doesn't deal with, it would be great if you could tell me the steps to replicate said bug.

**Review by chamod-gamage — APPROVED** [review]
Tried my best to break things but couldn't - great work!

**Review by jennifer-lu — APPROVED** [review]
Looks good to me! All the testing steps work well, couldn't break it. Great work!

**Review by tawnyzhao — APPROVED** [review]
Looks good, but I'm not sure this will resolve all the bugs. I'll try and recreate some of these in my spare tiem

**Pull request merged**
