### PR TITLE
[Module Experience] Breakpoints

### PR DESCRIPTION
**Pull request by ChinemeremChigbo**
## Notion ticket link

[[Module Experience] Breakpoints](https://www.notion.so/uwblueprintexecs/Module-Experience-Breakpoints-f5c6b0b1e8114b218f4e9724796b026c)

## Implementation description
* Fixed the responsive design for the /module/[moduleID] page
* Allowed interaction with the module/[moduleID] page

## Steps to test
1. Make a module and take note it it's generated ID in the url (after saving)
2. Navigate to localhost::3000/module/moduleID
3. Ensure that the module looks like it did in the preview
4. Ensure that you can check any multiplechoice/multiselect boxes, and write in any appropriate text fields in the moduleID page but not on the module creation page
5. Check for any new bugs on the module creation and module viewing pages and tell @ChinemeremChigbo if any are found 

## What should reviewers focus on?
* The module interaction page

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

### CODE REVIEW

**Review by jennifer-lu — APPROVED** [review]
Great work! The module page looks pretty sweet 💯. All of the testing steps worked well, and the page is responsive.

One nitpick is that the short answer and multi-select components are focusable (it would be nice if they had `pointerEvents="none"` like the multiple choice):

Screen Shot 2022-02-24 at 7 43 44 PM

Also, I'm not sure if this is within the scope of this ticket, but changes made on the module page (i.e. `localhost:3000/module/[id]` don't persist (e.g. when I select some multiple choice or enter text in short answer and press next and then prev, my changes are gone).

**Review by chamod-gamage — APPROVED** [review]
Great work 🔥

**Comment by ChinemeremChigbo** [comment]
> pointerEvents="none"

Fixed! Please take another look if you have the chance and let me know if things seem alright

**Comment by jennifer-lu** [comment]
Fixes look good to me!

Sorry I didn't catch this in the first review, but it seems that buttons are also clickable and focusable on the builder page which leads to some errors:

Screen Shot 2022-02-26 at 10 32 39 AM

I think `pointerEvents="none"` should work for this too.

**Comment by jennifer-lu** [comment]
@ChinemeremChigbo Looks super 🚀 great work!

**Review by tawnyzhao — APPROVED** [review]
Great :)

**Review by chamod-gamage — APPROVED** [review]
Great work on adding the requested spacing!

**Pull request merged**
