### PR TITLE
[Toolkit Landing Page] Fetch data from backend on toolkit landing page

### PR DESCRIPTION
**Pull request by jennifer-lu**
## Notion ticket link

[[Toolkit Landing Page] Toolkit landing page fetches data from backend](https://www.notion.so/uwblueprintexecs/Toolkit-Landing-Page-Toolkit-landing-page-fetches-data-from-backend-12c599dd77804afdb9b2d451830beec4)

## Implementation description
* Used `useSWR` to fetch data from backend
* Mapped data to `UserToolCard` components
* Followed original styling
* Used `useRouter` to route `UserToolCard` button clicks

## Steps to test
1. Go to `http://localhost:3000/`
2. Observe that tool cards are displayed with data from the backend; main page content should look something like this:
Screen Shot 2022-01-20 at 10 28 54 PM

3. Click on a continue learning button
4. Observe redirect to `http://localhost:3000/tool?id=<_id>` (note that page does not exist)
5. Go to `http://localhost:3000/`
6. Click on a self check button
7. Observe redirect to `http://localhost:3000/selfCheck?id=<selfCheckGroupID>` (note that page does not exist)

## What should reviewers focus on?
* Does it work?
* Does the code look ok?
* Does the styling look ok?

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

### CODE REVIEW

**Comment by ChinemeremChigbo** [comment]
Absolutely wonderful work! The only thing that I don't think is being parsed properly is image={thumbnail}.

On an aside @tawnyzhao the checking for duplicates in post.ts and update.ts for pages/api/tool is not working as intended. Currently, a tool can be assigned to a module, but after being saved, cannot be saved again since that module is already assigned to a tool. Also, this same tool can then be assigned to a different module and have both modules be assigned to the same tool.

I think instead we should add a check to see if the tool the module is already assigned to is the same tool that is calling the update request, and if so, not throw an error. Also, if the tool is updated and was previously linked to another module, that previous module needs to be unlinked from the tool if the request to link the tool to the new module is successful.

**Review by ChinemeremChigbo — CHANGES_REQUESTED** [review]
see comment.

**Comment by jennifer-lu** [comment]
> Absolutely wonderful work! The only thing that I don't think is being parsed properly is image={thumbnail}.

Thanks @ChinemeremChigbo ! I'm not sure which value should be passed as the image, for reference this is the data returned for one of the cards:

```
__v: 0
_id: "61ea146749b4de82699157cb"
createdAt: "2022-01-21T02:03:19.432Z"​​
createdBy: Array [ "John Doe" ]
description: "Necessitatibus omnis iste dolor officiis possimus velit quia atque. Tenetur vel porro."
editing: false
externalResources: Array(3) [ (2) […], (2) […], (2) […] ]
linkedModuleID: "61ea146749b4de82699157cf"
​​relatedResources: Array(3) [ (2) […], (2) […], (2) […] ]
​​relatedStories: Array(3) [ (2) […], (2) […], (2) […] ]
​​relatedToolsIDs: Array(3) [ "", "61ea146749b4de82699157ce", "61ea146749b4de82699157cc" ]
​​​selfCheckGroupID: "61ea146749b4de8269915760"
​​status: "published"
​​thumbnail: "http://abner.name"
​​title: "molestiae qui enim"
​​type: "Problem"
​​updatedAt: "2022-01-21T02:03:19.432Z"
​​video: "https://curt.info"
```

**Comment by ChinemeremChigbo** [comment]
> > Absolutely wonderful work! The only thing that I don't think is being parsed properly is image={thumbnail}.
> 
> Thanks @ChinemeremChigbo ! I'm not sure which value should be passed as the image, for reference this is the data returned for one of the cards:
> 
> ```
> __v: 0
> _id: "61ea146749b4de82699157cb"
> createdAt: "2022-01-21T02:03:19.432Z"​​
> createdBy: Array [ "John Doe" ]
> description: "Necessitatibus omnis iste dolor officiis possimus velit quia atque. Tenetur vel porro."
> editing: false
> externalResources: Array(3) [ (2) […], (2) […], (2) […] ]
> linkedModuleID: "61ea146749b4de82699157cf"
> ​​relatedResources: Array(3) [ (2) […], (2) […], (2) […] ]
> ​​relatedStories: Array(3) [ (2) […], (2) […], (2) […] ]
> ​​relatedToolsIDs: Array(3) [ "", "61ea146749b4de82699157ce", "61ea146749b4de82699157cc" ]
> ​​​selfCheckGroupID: "61ea146749b4de8269915760"
> ​​status: "published"
> ​​thumbnail: "http://abner.name"
> ​​title: "molestiae qui enim"
> ​​type: "Problem"
> ​​updatedAt: "2022-01-21T02:03:19.432Z"
> ​​video: "https://curt.info"
> ```

You are passing thumbnail, which is correct. But try this:
1. Make a new tool at localhost:3000/admin/dashboard/tools and set its thumbnail to:
https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/close-up-of-flower-blooming-outdoors-royalty-free-image-739387273-1544039749.jpg
2. Fill out all other required fields in the tool and self check
3. Publish the tool
4. Note that the thumbnail does not show as expected on the newly created module back at localhost/3000

This is as opposed to setting the image = {thumbnail} directly to image="https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/close-up-of-flower-blooming-outdoors-royalty-free-image-739387273-1544039749.jpg"

**Comment by jennifer-lu** [comment]
> You are passing thumbnail, which is correct. But try this:
> 
>     1. Make a new tool at localhost:3000/admin/dashboard/tools and set its thumbnail to:
>        https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/close-up-of-flower-blooming-outdoors-royalty-free-image-739387273-1544039749.jpg
> 
>     2. Fill out all other required fields in the tool and self check
> 
>     3. Publish the tool
> 
>     4. Note that the thumbnail does not show as expected on the newly created module back at localhost/3000
> 
> 
> This is as opposed to setting the image = {thumbnail} directly to image="https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/close-up-of-flower-blooming-outdoors-royalty-free-image-739387273-1544039749.jpg"

I see, great catch! Turns out I had a typo for thumbnail.

**Review by ChinemeremChigbo — APPROVED** [review]
WOOOO!!!! Looks absolutely rad. Great work.
image

**Comment by chamod-gamage** [comment]
Great work @jennifer-lu! Looks amazing :)
Thanks for the quick review and bug find @ChinemeremChigbo!
@tawnyzhao [I created a Notion ticket for that bug ](https://www.notion.so/uwblueprintexecs/Backend-Tool-Module-Link-Update-Bugs-7a2bd73d0d324ac7be3bacb7c73589d5) - I'll leave it to you to delegate and estimate

**Comment by jennifer-lu** [comment]
Thank you for the reviews! I will merge the pr :)

**Pull request merged**
