### PR TITLE
Module experience user input

### PR DESCRIPTION
**Pull request by ChinemeremChigbo**
## Notion ticket link

[[Module Experience] User Input](https://www.notion.so/uwblueprintexecs/Module-Experience-User-Input-251594ce49dc4c97a5c1d55053e05eba)

## Implementation description
* Sets UserInput state when a user types in a module

## Steps to test
1. Create a module with at least 1 of each editable field (multiple choice, multiselect and short answer) and note its ID
2. While creating your module, ensure the module builder behaves as expected (still cannot edit fields in the module preview, can add new slides and buttons as usual)
3. Add a console.log(userInput) to line 32 of pages/module/[module]
image
4. Navigate to http://localhost:3000/module/YOUR_MODULE_ID
5. Keep your browser's devtools console tab open as you edit the editable fields and take note of the changing userInput. If there are any errors, the schema doesn't behave as you expect, or you think I should do something differently (eg. delete items instead of setting them to false for multiselect) let me know!

## What should reviewers focus on?
* Module set state is working as intended

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

### CODE REVIEW

**Review by jennifer-lu — CHANGES_REQUESTED** [review]
Nice work! Testing is mostly working for me, and the `userInput` object is structured very intuitively.

It seems that the `userInput` is not updated correctly when multiselects are reselected. For example, select a multiselect option, deselect the same option, reselect the same option, make another edit, and observe that the option is still `false` in the `userInput` object:

Screen Shot 2022-03-17 at 7 49 19 PM

**Comment by jennifer-lu** [comment]
Also, I'm not sure if this was part of the previous behaviour, or within the scope of this pr, but the actual user input displayed on the form doesn't persist after switching slides. (The `userInput` object correctly maintains the state).

**Comment by ChinemeremChigbo** [comment]
> Also, I'm not sure if this was part of the previous behaviour, or within the scope of this pr, but the actual user input displayed on the form doesn't persist after switching slides. (The `userInput` object correctly maintains the state).

Yeah, this is covered by my next PR I believe

**Comment by ChinemeremChigbo** [comment]
> Nice work! Testing is mostly working for me, and the `userInput` object is structured very intuitively.
> 
> It seems that the `userInput` is not updated correctly when multiselects are reselected. For example, select a multiselect option, deselect the same option, reselect the same option, make another edit, and observe that the option is still `false` in the `userInput` object:
> 
> Screen Shot 2022-03-17 at 7 49 19 PM

fixed!

**Review by jennifer-lu — APPROVED** [review]
Looks good to me! Great work 💯

**Review by chamod-gamage — APPROVED** [review]
Amazing work!! LGTM~

**Pull request merged**
