### PR TITLE
Data Fetching for One Tool

### PR DESCRIPTION
**Pull request by Het7**
## Notion ticket link

[Tool landing page data fetching](https://uwblueprintexecs.notion.site/Tool-Landing-Page-Tool-landing-page-data-fetching-13dfb545c1774cd6ad02a2a0b62c15f9)

## Implementation description
This ticket fetches the tool information for a specific tool using the `/api/tool/{id}` api call. It grabs all the information for the tool and displays it on the page with minimal design. 

## Steps to test
1. Create a tool
2. Copy the tool id and paste it into this route: `locahost:3000/tool?id=<INSERT TOOL ID>`

## What should reviewers focus on?
* Ensure all the necessary information is being displayed

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

### CODE REVIEW

**Comment by ChinemeremChigbo** [comment]
Looks pretty good. But you have to lint your files so that the checks stop failing:
image
You need to get the appropriate formatter from the VSCode Extension store (i think we use ESLint) and then run the "yarn lint" in the command line (like you would run yarn dev). If yarn lint doesnt work for you (it doesn't for me) go the affected files: 
image
and fix the related errors:
image
This can usually be done in one move using the command (Shift + Option + F) - MacOS or (Shift + Alt + F) - Windows.

**Review by ChinemeremChigbo — COMMENTED** [review]
see comment

**Comment by Het7** [comment]
> Looks pretty good. But you have to lint your files so that the checks stop failing: image You need to get the appropriate code formatter from the VSCode Extension store (i think we use ESLint) and then run the "yarn lint" in the command line (like you would run yarn dev). If yarn lint doesnt work for you (it doesn't for me) go the affected files: image and fix the related errors: image This can usually be done in one move using the command (Shift + Option + F) - MacOS or (Shift + Alt + F) - Windows while in the unlinted file.

Thanks for the review @ChinemeremChigbo! I've applied linting!

**Review by chamod-gamage — APPROVED** [review]
Great work! I see that all the information is being displayed on the tool page :)

**Review by ChinemeremChigbo — APPROVED** [review]
Sick! Works great. Have we thought about how admins are going to host their photo / video files? A note if they use youtube videos they have to use the "embed" type link for it to work properly with Iframes eg typing https://www.youtube.com/embed/TBqRiIJpEXo into the link field instead of https://www.youtube.com/watch?v=TBqRiIJpEXo

**Comment by chamod-gamage** [comment]
> Sick! Works great. Have we thought about how admins are going to host their photo / video files? A note if they use youtube videos they have to use the "embed" type link for it to work properly with Iframes eg typing https://www.youtube.com/embed/TBqRiIJpEXo into the link field instead of https://www.youtube.com/watch?v=TBqRiIJpEXo

I think we'll likely just import/duplicate the code we use in the MD renderer to display videos/images (I believe we're relying on a library that converts to embeds under the hood for videos)

**Review by tawnyzhao — APPROVED** [review]

**Pull request merged**
