### PR TITLE
Tool Builder Linking and Publishing

### PR DESCRIPTION
**Pull request by ChinemeremChigbo**
## Notion ticket link

[[Tool Builder] Linking and Publishing Resolve Bugs](https://www.notion.so/uwblueprintexecs/Tool-Builder-Linking-and-Publishing-4c41f00dcb554c8daa01dd4bcd862518)

## Implementation description
- [x] Unpublish tool on save
- [x] Allow module linking without clicking into specific tool
- [x] Make Unpublish and link buttons work as intended
- [x] Don't allow publishing unless all fields are filled (check on publish click)
image
 image

## Steps to test
1. Make 2 new tools
2. Go back to the admin/dashboard/tools page and ensure that you can link a module to the first tool (you will need at least 1 module not currently linked to a tool)
3. Make sure you are unable to link the second tool to the same module
4. Fill out all the required fields on one of you tools and try publishing it from the admin/dashboard/tools page
5. Try unpublishing said tool from the same page
6. Try unlink the tool
7. Repeat steps 2 - 6 in random orders and ensure that no unexpected bugs occur

## What should reviewers focus on?
* Module unlinking, linking, publishing, unpublishing

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

### CODE REVIEW

**Comment by ChinemeremChigbo** [comment]
One thing of note is to do with the publish button state. While editing a tool, the "publish" button  is greyed out if the required fields are not filled out. This is not currently done in the the admin/dashboard/tools page as this page only checks if the tool is linked to a module and sets the publish button disabled state off of that. I don't think this should be the case, however the alternative seems to be duplicating the code from the tool builder (a very large function that needs to basically check all required fields as well as self check questions. Should I duplicate this code, leave the publish discrepancy as is (and let admins be sure that a tool is ready before publishing), or remove the nested function from the self check code.

**Comment by chamod-gamage** [comment]
> One thing of note is to do with the publish button state. While editing a tool, the "publish" button is greyed out if the required fields are not filled out. This is not currently done in the the admin/dashboard/tools page as this page only checks if the tool is linked to a module and sets the publish button disabled state off of that. I don't think this should be the case, however the alternative seems to be duplicating the code from the tool builder (a very large function that needs to basically check all required fields as well as self check questions to make sure everything is filled out). Should I duplicate this code, leave the publish discrepancy as is (and let admins be sure that a tool is ready before publishing), or remove the nested function from the self check code. I think it would make the most sense if the 2 published buttons (inside the actual tool and on the tools landing page, behaved the same way).
> 
> This also ties in to a larger topic of the self check code, for instance I currently am perpetually checking to ensure the tool is publishable, which works fine for the most part, but I am also not sure how big these self check questionnaires will get. I note some slowdowns after adding ~20 questions which might be largely due to continual checking both for the submission as well as the fact that we're running on dev and not prod. The code I have written has it's flaws so I am really open to any suggestions, my current ideas include only checking when the mouse is within the radius of the submission button, leaving it as is since it will probably run fine on prod, or getting rid of it entirely since we can trust the admins to deduce when the required fields are filled ? Any thoughts?

I'm going to bring your questions up to the rest of p-team but my thoughts are:

1. Maybe we can keep the Publish button active whenever a module has been linked but run a function that checks whether the given tool is fully publishable on click. If the function deems the tool valid it just publishes but if not, it would pop a modal up saying that there are missing fields and a CTA to edit the tool.
2. We'll ask about the maximum on questions in a Self Check at the client meeting on Monday but I doubt that there will be more than 10 questions.

**Review by chamod-gamage — COMMENTED** [review]
https://www.loom.com/share/8338da6de9fc49358bcc2c69c0859c28

Things are working well for the most part, able to publish and unpublish tools with linked modules from the Tool page and linked modules are not available to select from other tools.

However, from the video, you can see that sometimes when accessing the Tool Builder itself the linked module does not appear as an option nor as something that's selected which makes it impossible to publish from the tool builder. However, the module is still linked because I can publish and unpublish from the dashboard and it sometimes does appear (I think after publishing it appears consistently but without publishing it doesn't but this pattern could be a coincidence).

**Comment by ChinemeremChigbo** [comment]
> [loom.com/share/8338da6de9fc49358bcc2c69c0859c28](https://www.loom.com/share/8338da6de9fc49358bcc2c69c0859c28)
> 
> Things are working well for the most part, able to publish and unpublish tools with linked modules from the Tool page and linked modules are not available to select from other tools.
> 
> However, from the video, you can see that sometimes when accessing the Tool Builder itself the linked module does not appear as an option nor as something that's selected which makes it impossible to publish from the tool builder. However, the module is still linked because I can publish and unpublish from the dashboard and it sometimes does appear (I think after publishing it appears consistently but without publishing it doesn't but this pattern could be a coincidence).

Thank you for catching this! Will look into it.

**Comment by ChinemeremChigbo** [comment]
> > One thing of note is to do with the publish button state. While editing a tool, the "publish" button is greyed out if the required fields are not filled out. This is not currently done in the the admin/dashboard/tools page as this page only checks if the tool is linked to a module and sets the publish button disabled state off of that. I don't think this should be the case, however the alternative seems to be duplicating the code from the tool builder (a very large function that needs to basically check all required fields as well as self check questions to make sure everything is filled out). Should I duplicate this code, leave the publish discrepancy as is (and let admins be sure that a tool is ready before publishing), or remove the nested function from the self check code. I think it would make the most sense if the 2 published buttons (inside the actual tool and on the tools landing page, behaved the same way).
> > This also ties in to a larger topic of the self check code, for instance I currently am perpetually checking to ensure the tool is publishable, which works fine for the most part, but I am also not sure how big these self check questionnaires will get. I note some slowdowns after adding ~20 questions which might be largely due to continual checking both for the submission as well as the fact that we're running on dev and not prod. The code I have written has it's flaws so I am really open to any suggestions, my current ideas include only checking when the mouse is within the radius of the submission button, leaving it as is since it will probably run fine on prod, or getting rid of it entirely since we can trust the admins to deduce when the required fields are filled ? Any thoughts?
> 
> I'm going to bring your questions up to the rest of p-team but my thoughts are:
> 
> 1. Maybe we can keep the Publish button active whenever a module has been linked but run a function that checks whether the given tool is fully publishable on click. If the function deems the tool valid it just publishes but if not, it would pop a modal up saying that there are missing fields and a CTA to edit the tool. Closing the modal just returns the user to the status quo tools page.
>    Ideally we won't duplicate code and instead hopefully be able to abstract this code out but if not, duplication is okay too.
> 2. We'll ask about the maximum on questions in a Self Check at the client meeting on Monday but I doubt that there will be more than 10 questions.

Your first suggestion makes sense and I'll probably implement that unless @tawnyzhao thinks otherwise. Do you think the same should be done within a module itself? Or is the performance fine?

**Comment by chamod-gamage** [comment]
> > > One thing of note is to do with the publish button state. While editing a tool, the "publish" button is greyed out if the required fields are not filled out. This is not currently done in the the admin/dashboard/tools page as this page only checks if the tool is linked to a module and sets the publish button disabled state off of that. I don't think this should be the case, however the alternative seems to be duplicating the code from the tool builder (a very large function that needs to basically check all required fields as well as self check questions to make sure everything is filled out). Should I duplicate this code, leave the publish discrepancy as is (and let admins be sure that a tool is ready before publishing), or remove the nested function from the self check code. I think it would make the most sense if the 2 published buttons (inside the actual tool and on the tools landing page, behaved the same way).
> > > This also ties in to a larger topic of the self check code, for instance I currently am perpetually checking to ensure the tool is publishable, which works fine for the most part, but I am also not sure how big these self check questionnaires will get. I note some slowdowns after adding ~20 questions which might be largely due to continual checking both for the submission as well as the fact that we're running on dev and not prod. The code I have written has it's flaws so I am really open to any suggestions, my current ideas include only checking when the mouse is within the radius of the submission button, leaving it as is since it will probably run fine on prod, or getting rid of it entirely since we can trust the admins to deduce when the required fields are filled ? Any thoughts?
> > 
> > 
> > I'm going to bring your questions up to the rest of p-team but my thoughts are:
> > 
> > 1. Maybe we can keep the Publish button active whenever a module has been linked but run a function that checks whether the given tool is fully publishable on click. If the function deems the tool valid it just publishes but if not, it would pop a modal up saying that there are missing fields and a CTA to edit the tool. Closing the modal just returns the user to the status quo tools page.
> >    Ideally we won't duplicate code and instead hopefully be able to abstract this code out but if not, duplication is okay too.
> > 2. We'll ask about the maximum on questions in a Self Check at the client meeting on Monday but I doubt that there will be more than 10 questions.
> 
> Your first suggestion makes sense and I'll probably implement that unless @tawnyzhao thinks otherwise. Do you think the same should be done within a module itself? Or is the performance fine?

I think the performance is fine at reasonable numbers of Self Check Q, but just in case let's hold off until after the client meeting today (feel free to come if you're not busy and are free!) when I'll have a definitive answer to you about the upper bound on self check questions.

**Review by chamod-gamage — APPROVED** [review]
Working beautifully 😍 
Amazing work! Didn't look much at the code but from a product perspective this is perfect

**Review by tawnyzhao — APPROVED** [review]

**Pull request merged**
